language: node_js
matrix:
  include:
    - node_js: "12"
    - node_js: "10"
    - node_js: "8"
      env: COVER=yes
before_install:
  - 'npm install -g npm@latest'
script:
  - 'if [ -n "$COVER" ]; then npm run test-cover; else npm test; fi'
after_success:
  - 'if [ -n "$COVER" ]; then ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls; fi'
