language: node_js
matrix:
  include:
  - node_js: "12"
  - node_js: "10"
    env: COVER=true
before_install:
- 'npm install -g npm@latest'
script:
- if [ "$COVER" = true ]; then
    npm run test-cover;
  else
    npm test;
  fi
after_success:
- if [ "$COVER" = true ]; then
    ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls;
  fi
